apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: fitnessappnamespace
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: app.fitness.tld
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fitnessappservice
            port:
              number: 80