apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitnessapp-deployment #name it 
  namespace: fitnessappnamespace
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fitnessapp 
  template:
    metadata:
      labels:
        app:  fitnessapp
    spec:
      containers:
      - name: fitnessapp  
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        envFrom: 
        - configMapRef:
            name: app-config