apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitnessapp-deployment #name it 
  namespace: fitnessappnamespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fitnessapp #change dis vaddd?
  template:
    metadata:
      labels:
        app:  fitnessapp
    spec:
      containers:
      - name: fitnessapp  #yolo
        image: robonon/fitnessapp:latest #change this 
        ports:
        - containerPort: 80
        envFrom: 
        - configMapRef:
            name: app-config