---
- name: Deploy Helm Charts to AKS
  hosts: localhost
  gather_facts: false
  vars_files:
    - helm_vars.yaml

  tasks:
    - name: Deploy Helm Charts
      kubernetes.core.helm:
        name: "{{ item.name }}"
        chart_reference: "{{ item.chart_reference }}"
        values_files:
          - "{{ item.values_file }}"
        state: "{{ helm_deploy_state }}"
        kubeconfig: "~/.kube/config"
      with_items: "{{ helm_charts }}"
