---
- name: Deploy All-in-One Solution on Azure
  hosts: localhost
  gather_facts: false
  vars_files:
    - helm_vars.yaml
    - terraform_vars.yaml

  tasks:
  - name: Deploy kubernetes cluster with Terraform
    community.general.terraform:
      plan_file: "../Azure/main.tfplan"
      project_path: "../Azure" 
  # - name: Deploy Terraform Infrastructure
  #   azure.azcollection.azure_rm_deployment:
  #     auth_source: env
  #     resource_group: "{{ resource_group }}"
  #     template_link: "./path/to/your/terraform/template.json"
  #     deployment_mode: complete
  #   delegate_to: localhost

  - name: Deploy Helm Charts
    kubernetes.core.helm:
      name: "{{ item.name }}"
      release_name: "{{ item.name }}"
      release_namespace: "fitnessapp"
      chart_ref: "{{ item.chart_ref }}"
      values_files:
        - "{{ item.values_file }}"
      state: "{{ helm_deploy_state }}"
    with_items: "{{ helm_charts }}"
    become: yes
