---
- name: Deploy Terraform Infrastructure on Azure
  hosts: localhost
  gather_facts: false
  vars_files:
    - terraform_vars.yaml
  tasks:
    - name: Include Azure Login
      include_role:
        name: azure.azure_preview_modules

    - name: Login to Azure
      azure_login:
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_client_secret }}"
        subscription_id: "{{ azure_subscription_id }}"
        tenant: "{{ azure_tenant_id }}"
      delegate_to: localhost

    - name: Deploy Terraform Template
      community.general.azure_rm_deployment:
        resource_group: "{{ resource_group }}"
        template_path: "./path/to/your/terraform/template.json"
        parameters:
          param1: "value1"
          param2: "value2"
        mode: Complete
      delegate_to: localhost
