apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: fitnessappnamespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api 
  template:
    metadata:
      labels:
        app:  api
    spec:
      containers:
      - name: api  
        image: robonon/workoutbuilderapi:latest  
        ports:
        - containerPort: 80
        envFrom: 
        - configMapRef:
            name: api-config