apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init-job
spec:
  template:
    spec:
      containers:
      - name: mongo-init-container
        image: larsappel/my-mongo-init:latest
        env:
        - name: MONGO_HOST
          value: mongodb-service
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_COLLECTION_NAME
          value:
        - name: MONGO_DATABASE_NAME
          value:
        - name: MONGO_CONNECTION_STRING
          value:
      restartPolicy: OnFailure